### ISSUE TITLE
Error trying to configure Icons

### ISSUE THREAD

**Issue by Mat-moran** [Code-Forge-Net/Remix-Dev-Tools#101]
Hi,

I am trying to following your video series to configure RDT and I found a problem when I add `icon-library.tsx` 

This is a typescript problem that seems to not find the `Plugin` type. 
![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/4810013/4581064b-1d74-4dfe-b0b4-9c4c567378c5)

Here is another Error the console launch when I add `icon-library.tsx` file to the plugin folder.
![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/4810013/c7fd57f8-d40c-4097-bf71-5a21446c3e87)

Did I misconfigure something or it is small bug in the plugin?

Thanks

**Comment by AlemTuzlak** [comment]
@Mat-moran Hey! Sorry for the late response, so the issue is that the Plugin type is now called RdtPlugin, the easiest way to add it to your project on Vite is just to not use the type at all,  I've added it in this video:
https://youtu.be/gG8BVFyVBmY
so you can figure out what I did but I'll fix this soon!
