### ISSUE TITLE
Infinite Loop with showRouteBoundaries prop

### ISSUE THREAD

**Issue by xHomu** [Code-Forge-Net/Remix-Dev-Tools#21]
Edit: After preliminary debugging with @AlemTuzlak, it appears to be related to url SearchParams on your entry page.

---

Not quite sure if there's something particular with our app or is it with the new feature, but turning on showRouteBoundaries causes our home page to infinite loop:

![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/c02a95e9-3e18-4508-b1f8-7f5d0ae08d2a)

Disabling it and RDT works just as expected.

Repo: https://github.com/manawiki/core

If you want to take a look @AlemTuzlak , I'll dm you the env variables.

**Comment by AlemTuzlak** [comment]
@xHomu after an investigation I've figured out that the issue is within manawiki theme provider. it seems to cause some sort of infinite refresh of the devtools, dev tools should not be wrapped in providers to ensure that they are not re-rendered all the time but rather on the root of the project. We can discuss further on discord

**Comment by xHomu** [comment]
For future reference, this was the solution after Alem spent time debugging it:

![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/e19fea64-a22a-449f-a091-46a0dc132da2)
