### ISSUE TITLE
Using Remix Devtools screws up outletContext

### ISSUE THREAD

**Issue by arunmmanoharan** [Code-Forge-Net/Remix-Dev-Tools#52]
Hi, I have an app which uses outletContext to send data to children. If I keep the Remix Devtools in the root, changing routes forces a rerender and outlet state gets reset. Can you please help me out?

This is my code.

https://github.com/arunmmanoharan/remix-outlet-demo

**Comment by AlemTuzlak** [comment]
@arunmmanoharan can you check this with the latest version?

**Comment by arunmmanoharan** [comment]
Now its working. What was the issue if I may ask?

**Comment by AlemTuzlak** [comment]
@arunmmanoharan of course you may. The underlying issue is the code that hooks into remix internals to show route boundaries, in the latest release I have hidden it behind a feature flag due to this fact, it uses a useEffect which remounts your component if you submit to the current page and causes all sorts of issues in this case, I have discovered this a few days ago and I am working on a fix but until then it's disabled by default to not cause issues for anyone. Hence why this issue isn't closed, because the bug is not yet fixed. But I hope to have it resolved soon with v3! (So please keep the repro-repo open until then so I can test that it works for you again)

**Comment by AlemTuzlak** [comment]
@arunmmanoharan this should be fixed with v3, can you confirm,?

**Comment by AlemTuzlak** [comment]
Closing, feel free to open if it's still an issue!
