### ISSUE TITLE
websocket port

### ISSUE THREAD

**Issue by T-Nagui** [Code-Forge-Net/Remix-Dev-Tools#75]
I'm using RDT version 3 with remix 2.3 
`dev: "PORT=4000 dotenv -e .env.local remix dev -c \"rdt-serve ./build/index.js\" --manual"`
I'm actually using remix dev for the server without any custom server and  port 80 for third api with remix and i can't replaced with any other port. but websocket of RDT is taking 8080
`const port = (config == null ? void 0 : config.wsPort) || 8080;` 
how i can change that port without creating a custom server ?  it's possible to use flag (--port 8181) ?

**Comment by AlemTuzlak** [comment]
Unfortunately at the moment there is no way to do it, and I don't think I'll be adding it because I plan to move onto Remix + Vite only support after it is stabilized. What you can do though is use a minimal express server and set this up, the idea of using the CLI command is if you don't care at all about your server setup, if you do you should move onto the next best thing. If you haven't gotten very far with your project you could switch to Vite as well where this is not needed at all!
