### ISSUE TITLE
`remix-development-tools/server` has no exports

### ISSUE THREAD

**Issue by micmcgrorty** [Code-Forge-Net/Remix-Dev-Tools#84]
![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/37194621/5bf960fb-0d70-43ef-b954-7dc19d78b820)

We've recently upgraded our app to Remix version 2, and I've just come to update RDT to the latest version. We use a custom server, so have to do the server side set-up as well. 

After following the documentation I've found that `remix-development-tools/server` doesn't export the functions required by the documentation.

This is with the latest version of RDT.

**Comment by AlemTuzlak** [comment]
@micmcgrorty sorry for taking a while, does ot still work though? I'm guessing it does but the types are not?

**Comment by brookslybrand** [comment]
I also noticed this with `remix-development-tools/vite`. [Here's an example](https://stackblitz.com/edit/remix-run-remix-qrkkuu?file=vite.config.mjs) (from another issue, but you can see the types don't exist

**Comment by AlemTuzlak** [comment]
@brookslybrand thank you for a repro, I'll look into this, I know that node doesn't handle imports from submodules really great, but I can't say if it's that ir some issue with typing. I'll see if I can narrow it down

**Comment by AlemTuzlak** [comment]
If you se the module to ESNext in your tsconfig.json does that resolve the types properly?

**Comment by fobos531** [comment]
> If you se the module to ESNext in your tsconfig.json does that resolve the types properly?

I have the module to ESNext but the types are not properly resolved for me (using `remix-development-tools/vite`)

**Comment by AlemTuzlak** [comment]
@brookslybrand @fobos531 @micmcgrorty  I've figured out the root cause, you can find it here on this stack overflow thread:
https://stackoverflow.com/questions/76236503/not-able-to-get-typescript-definitions-working-when-using-subpath-exports

But the TL:DR; is that you have to set the moduleResolution to "NodeNext" or "node16", the "Bundler" option doesn't pick up the types, I think "NodeNext" for ESM and "node16" for CJS should be fine in these cases
